In [1]:
import pandas as pd     #(version 1.0.0)
import plotly           #(version 4.5.4) pip install plotly==4.5.4
import plotly.express as px
import plotly.graph_objs as go

import dash             #(version 1.9.1) pip install dash==1.9.1
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
from datetime import datetime as dt

app = dash.Dash(__name__)

In [4]:
df = pd.read_csv("patients-maroc.csv")
df

,n,sex,age,country,province,disease,group,exposure_start,exposure_end,infection_reason,infection_order,infected_by,contact_number,confirmed_date,released_date,deceased_date,state
0,0,male,39.0,Maroc,Casablanca - Settat,NaN,NaN,NaN,NaN,Imported,NaN,NaN,NaN,3/2/20,3/17/20,NaN,Exit
1,1,female,89.0,Maroc,Casablanca - Settat,1.0,NaN,NaN,NaN,Imported,NaN,NaN,NaN,3/5/20,NaN,3/10/20,Deceased
2,2,male,59.0,France,Marrakech - Safi,NaN,NaN,3/7/20,NaN,Imported,NaN,NaN,NaN,3/10/20,3/29/20,NaN,Exit
3,3,female,NaN,France,Marrakech - Safi,NaN,NaN,3/7/20,NaN,Imported,NaN,NaN,NaN,3/11/20,3/29/20,NaN,Exit
4,4,female,1.0,France,Marrakech - Safi,NaN,NaN,3/7/20,NaN,Imported,NaN,NaN,NaN,3/11/20,3/29/20,NaN,Exit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1179,1179,NaN,NaN,NaN,Daraa - Tafilalet,NaN,NaN,NaN,NaN,Local,NaN,NaN,NaN,4/7/20,NaN,NaN,isolated
1180,1180,NaN,NaN,NaN,Daraa - Tafilalet,NaN,NaN,NaN,NaN,Local,NaN,NaN,NaN,4/7/20,NaN,NaN,isolated
1181,1181,NaN,NaN,NaN,Daraa - Tafilalet,NaN,NaN,NaN,NaN,Local,NaN,NaN,NaN,4/7/20,NaN,NaN,isolated
1182,1182,NaN,NaN,NaN,Daraa - Tafilalet,NaN,NaN,NaN,NaN,Local,NaN,NaN,NaN,4/7/20,NaN,NaN,isolated
1183,1183,NaN,NaN,NaN,Daraa - Tafilalet,NaN,NaN,NaN,NaN,Local,NaN,NaN,NaN,4/7/20,NaN,NaN,isolated

In [21]:
import matplotlib.pyplot as plt
import plotly.offline as pyo
import seaborn as sns

pyo.plot([{
    'x':df.state,
    'y':df.n
    
}])

'temp-plot.html'